import { XmasCardData, CardGrid } from '../../src/components/card-type';

export const cardData = {
  year: 2023,
  images: '2023/images',
  front: {
    cardGrid: {
      i: 'front.png',
      t: 'Christmas Card 2023',
      l: 'O-',
      s: 's-',
      w: 1024,
      h: 730,
      x: 5,
      y: 5,
      d: '',
      m: 0,
      n: 0,
    },
    cardData: [
      {
        i: 20,
        x: 490,
        y: 80,
        w: 60,
        h: 30,
        t: 'Christmas message 2023',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 1,
        x: 2,
        y: 0,
        w: 1,
        h: 2,
        t: 'Wild camping in Scotland on route to the Orkneys - Alison',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 12,
        x: 2,
        y: 2,
        w: 1,
        h: 1,
        t: 'Camping friends - Izora, Marion and Nigel - Forest of Dean',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 13,
        x: 4,
        y: 2,
        w: 1,
        h: 1,
        t: 'Pizza time - Dad, Geoff, Alison, Kay and Mum - 59 degrees North, Sanday',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 14,
        x: 4,
        y: 0,
        w: 1,
        h: 1,
        t: 'Cutting the grass in the Walled Garden - Alison - Saville, Sanday',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 15,
        x: 1,
        y: 2,
        w: 1,
        h: 1,
        t: 'Party on the beach - Geoff, Kay and Kaya - Backaskaill beach, Sanday',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 16,
        x: 2,
        y: 3,
        w: 1,
        h: 2,
        t: 'Rest stop from cycling from Inverness to the Orkneys - Alison - Brae Tongue',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 6,
        x: 3,
        y: 1,
        w: 1,
        h: 1,
        t: 'School girls unite - Ruby and Alison - Duxford Close, Cardiff',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 7,
        x: 0,
        y: 0,
        w: 1,
        h: 1,
        t: 'In the garden - Emily and Richard - Lansdowne Road, Cardiff',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 8,
        x: 4,
        y: 1,
        w: 1,
        h: 1,
        t: 'Party time with friend - Dave, Peter, Carol, Geoff, Maria, Julie and Alison - Basingstoke',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 9,
        x: 3,
        y: 3,
        w: 2,
        h: 2,
        t: 'Fairy cottage - Geoff, Malachi, Richard, Beatrice, Emily, Dakota, Alison, Ava, Izora and Aurora - Fonmon Castle',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 10,
        x: 0,
        y: 3,
        w: 2,
        h: 2,
        t: 'Family meal time - Aurora, Izora, Annette, Emily, Geoff, Dakota, Alison, (Ava) and Beatrice - Duxford Close, Cardiff',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 11,
        x: 3,
        y: 2,
        w: 1,
        h: 1,
        t: 'A drink with some friends - Brian, Teresa, Alison, Carol, Ann and Tony - Green Man, Harlow',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 0,
        x: 0,
        y: 2,
        w: 1,
        h: 1,
        t: 'Derelict cottage - Saville beach, Sanday',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 2,
        x: 1,
        y: 1,
        w: 1,
        h: 1,
        t: 'Pink Floyd experience - Geoff, Alison and Malachi - Zeiss Major Planetarium, Berlin',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 3,
        x: 0,
        y: 1,
        w: 1,
        h: 1,
        t: 'In the park without any children - Beatrice, Malachi and Alison - Berlin',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 4,
        x: 1,
        y: 0,
        w: 1,
        h: 1,
        t: 'Happy days - Malachi, Geoff and Beatrice - Berlin',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 5,
        x: 3,
        y: 0,
        w: 1,
        h: 1,
        t: 'Cocktail time - Alison and Annette - Herne Bay',
        d: '',
        m: 0,
        n: 0,
      },
    ],
  },
  back: {
    cardGrid: {
      i: 'back.png',
      t: 'Christmas Card 2023 back',
      l: 'B-',
      s: 's-',
      w: 1024,
      h: 730,
      x: 3,
      y: 3,
      d: '',
      m: 0,
      n: 0,
    },
    cardData: [
      {
        i: 7,
        x: 1,
        y: 0,
        w: 1,
        h: 2,
        t: 'In the park - Alison and Geoff - Berlin',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 3,
        x: 2,
        y: 2,
        w: 1,
        h: 1,
        t: 'Look at me - Izora and Geoff - Cardiff',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 6,
        x: 0,
        y: 1,
        w: 1,
        h: 2,
        t: 'Room for one more - Alison, Aurora, Ava, Alison, Izora and Dakota - Cardiff',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 4,
        x: 2,
        y: 1,
        w: 1,
        h: 1,
        t: 'Room on my dinosaur - Ava - Fonmon Castle',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 2,
        x: 0,
        y: 0,
        w: 1,
        h: 1,
        t: 'Looking gorgeous - Aurora - Berlin',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 5,
        x: 1,
        y: 2,
        w: 1,
        h: 1,
        t: 'We are family - Geoff, Mum, Alison, Dad and Rosie - Saville, Sanday',
        d: '',
        m: 0,
        n: 0,
      },
      {
        i: 1,
        x: 2,
        y: 0,
        w: 1,
        h: 1,
        t: "I'm so happy - Dakota - Berlin",
        d: '',
        m: 0,
        n: 0,
      },
    ],
  },
};
