"use strict";
/**
@license
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
Object.defineProperty(exports, "__esModule", { value: true });
exports.Card2023 = void 0;
exports.Card2023 = {
    year: '2023',
    images: '2023/images',
    front: {
        cardGrid: {
            i: 'front.png',
            t: 'Christmas Card 2023',
            l: 'l-',
            s: 's-',
            w: 1024,
            h: 730,
            x: 5,
            y: 5,
        },
        cardData: [
            {
                i: '00',
                x: 490,
                y: 80,
                w: 60,
                h: 30,
                t: 'Christmas message 2023',
            },
            {
                i: '1',
                x: 2,
                y: 0,
                w: 1,
                h: 2,
                t: 'Wild camping in Scotland on route to the Orkneys - Alison',
            },
            {
                i: '12',
                x: 2,
                y: 2,
                w: 1,
                h: 1,
                t: 'Camping friends - Izora, Marion and Nigel - Forest of Dean',
            },
            {
                i: '13',
                x: 4,
                y: 2,
                w: 1,
                h: 1,
                t: 'Pizza time - Dad, Geoff, Alison, Kay and Mum - 59 degrees North, Sanday',
            },
            {
                i: '14',
                x: 4,
                y: 0,
                w: 1,
                h: 1,
                t: 'Cutting the grass in the Walled Garden - Alison - Saville, Sanday',
            },
            {
                i: '15',
                x: 1,
                y: 2,
                w: 1,
                h: 1,
                t: 'Party on the beach - Geoff, Kay and Kaya - Backaskaill beach, Sanday',
            },
            {
                i: '16',
                x: 2,
                y: 3,
                w: 1,
                h: 2,
                t: 'Rest stop from cycling from Inverness to the Orkneys - Alison - Brae Tongue',
            },
            {
                i: '6',
                x: 3,
                y: 1,
                w: 1,
                h: 1,
                t: 'School girls unite - Ruby and Alison - Duxford Close, Cardiff',
            },
            {
                i: '7',
                x: 0,
                y: 0,
                w: 1,
                h: 1,
                t: 'In the garden - Emily and Richard - Lansdowne Road, Cardiff',
            },
            {
                i: '8',
                x: 4,
                y: 1,
                w: 1,
                h: 1,
                t: 'Party time with friend - Dave, Peter, Carol, Geoff, Maria, Julie and Alison - Basingstoke',
            },
            {
                i: '9',
                x: 3,
                y: 3,
                w: 2,
                h: 2,
                t: 'Fairy cottage - Geoff, Malachi, Richard, Beatrice, Emily, Dakota, Alison, Ava, Izora and Aurora - Fonmon Castle',
            },
            {
                i: '10',
                x: 0,
                y: 3,
                w: 2,
                h: 2,
                t: 'Family meal time - Aurora, Izora, Annette, Emily, Geoff, Dakota, Alison, (Ava) and Beatrice - Duxford Close, Cardiff',
            },
            {
                i: '11',
                x: 3,
                y: 2,
                w: 1,
                h: 1,
                t: 'A drink with some friends - Brian, Teresa, Alison, Carol, Ann and Tony - Green Man, Harlow',
            },
            {
                i: '0',
                x: 0,
                y: 2,
                w: 1,
                h: 1,
                t: 'Derelict cottage - Saville beach, Sanday',
            },
            {
                i: '2',
                x: 1,
                y: 1,
                w: 1,
                h: 1,
                t: 'Pink Floyd experience - Geoff, Alison and Malachi - Zeiss Major Planetarium, Berlin',
            },
            {
                i: '3',
                x: 0,
                y: 1,
                w: 1,
                h: 1,
                t: 'In the park without any children - Beatrice, Malachi and Alison - Berlin',
            },
            {
                i: '4',
                x: 1,
                y: 0,
                w: 1,
                h: 1,
                t: 'Happy days - Malachi, Geoff and Beatrice - Berlin',
            },
            {
                i: '5',
                x: 3,
                y: 0,
                w: 1,
                h: 1,
                t: 'Cocktail time - Alison and Annette - Herne Bay',
            },
        ],
    },
    back: {
        cardGrid: {
            i: 'back.png',
            t: 'Christmas Card 2023 back',
            l: 'bl-',
            s: 'bs-',
            w: 1024,
            h: 730,
            x: 3,
            y: 3,
        },
        cardData: [
            {
                i: '7',
                x: 1,
                y: 0,
                w: 1,
                h: 2,
                t: 'In the park - Alison and Geoff - Berlin',
            },
            {
                i: '3',
                x: 2,
                y: 2,
                w: 1,
                h: 1,
                t: 'Look at me - Izora and Geoff - Cardiff',
            },
            {
                i: '6',
                x: 0,
                y: 1,
                w: 1,
                h: 2,
                t: 'Room for one more - Alison, Aurora, Ava, Alison, Izora and Dakota - Cardiff',
            },
            {
                i: '4',
                x: 2,
                y: 1,
                w: 1,
                h: 1,
                t: 'Room on my dinosaur - Ava - Fonmon Castle',
            },
            {
                i: '2',
                x: 0,
                y: 0,
                w: 1,
                h: 1,
                t: 'Looking gorgeous - Aurora - Berlin',
            },
            {
                i: '5',
                x: 1,
                y: 2,
                w: 1,
                h: 1,
                t: 'We are family - Geoff, Mum, Alison, Dad and Rosie - Saville, Sanday',
            },
            {
                i: '1',
                x: 2,
                y: 0,
                w: 1,
                h: 1,
                t: "I'm so happy - Dakota - Berlin",
            },
        ],
    },
};
//# sourceMappingURL=xmas-2023.js.map